/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BankView;
import perbankan.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;



/**
 *
 * @author mapam
 */
public class BankView extends javax.swing.JFrame {

    /**
     * Creates new form BankView
     */
    private DefaultTableModel tableModel;
    private Bank bank;
    private int selectedRowIndex = -1;
    
    public BankView() {
        initComponents();
        tableModel = new DefaultTableModel(new Object[]{"Nama Awal", "Nama Akhir", "Saldo"}, 0);
        tableBank.setModel(tableModel);
        
        bank = new Bank();
        btnHapus.setEnabled(false);
        btnEdit.setEnabled(false);
        btnTarik.setEnabled(false);
        btnTambah.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNamaAwal = new javax.swing.JLabel();
        lblNamaAkhir = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableBank = new javax.swing.JTable();
        btnSimpan = new javax.swing.JButton();
        txtSaldo = new javax.swing.JTextField();
        txtNamaAwal = new javax.swing.JTextField();
        lblSaldo = new javax.swing.JLabel();
        txtNamaAkhir = new javax.swing.JTextField();
        btnHapus = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnTarik = new javax.swing.JButton();
        titleBank = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNamaAwal.setText("Nama Awal");

        lblNamaAkhir.setText("Nama Akhir");

        tableBank.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nama Awal", "Nama Akhir", "Saldo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableBank.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBankMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tableBankMouseExited(evt);
            }
        });
        jScrollPane3.setViewportView(tableBank);

        btnSimpan.setBackground(new java.awt.Color(0, 153, 204));
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        txtSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSaldoActionPerformed(evt);
            }
        });

        txtNamaAwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaAwalActionPerformed(evt);
            }
        });

        lblSaldo.setText("Saldo");

        btnHapus.setBackground(new java.awt.Color(255, 51, 0));
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(255, 255, 102));
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnTambah.setBackground(new java.awt.Color(204, 204, 204));
        btnTambah.setText("Setor");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnTarik.setBackground(new java.awt.Color(204, 204, 204));
        btnTarik.setText("Tarik");
        btnTarik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarikActionPerformed(evt);
            }
        });

        titleBank.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        titleBank.setText("BANK CUSTOMERS");

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(309, 309, 309)
                                .addComponent(lblSaldo))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(224, 224, 224)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblNamaAkhir, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblNamaAwal, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(btnSimpan)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnHapus)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnEdit)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnTambah)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnTarik))
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
                                        .addComponent(txtSaldo, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(btnReset))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(70, 70, 70)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNamaAwal, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtNamaAkhir))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(titleBank, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(titleBank)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNamaAwal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNamaAwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(lblNamaAkhir)
                .addGap(4, 4, 4)
                .addComponent(txtNamaAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSaldo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHapus)
                    .addComponent(btnSimpan)
                    .addComponent(btnEdit)
                    .addComponent(btnTambah)
                    .addComponent(btnTarik))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(btnReset)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        String namaAwal = txtNamaAwal.getText();
        String namaAkhir = txtNamaAkhir.getText();
        int saldo=0;
        //int index = bank.getJumlahNasabah();

        if (!txtSaldo.getText().isEmpty()) {
            try {
                saldo = Integer.parseInt(txtSaldo.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Saldo harus berupa angka", "Kesalahan", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        
        Nasabah nasabah = new Nasabah(namaAwal, namaAkhir);
        Tabungan tabungan = new Tabungan(saldo);
        nasabah.setTabungan(tabungan);
        bank.tambahNasabah(nasabah);

        tableModel.addRow(new Object[]{nasabah.getNamaAwal(), nasabah.getNamaAkhir(), tabungan.getSaldo()});
        clear();
        JOptionPane.showMessageDialog(this, "Data berhasil disimpan");
           
//        int saldo = txtSaldo.getText().equals("") ? 0 : Integer.parseInt(txtSaldo.getText());
//        if (!namaAwal.equals("") && !namaAkhir.equals("")){
//            this.bank
//        }
        
         
    }//GEN-LAST:event_btnSimpanActionPerformed
    
    private void clear(){
        txtNamaAwal.setText("");
        txtNamaAkhir.setText("");
        txtSaldo.setText("");
    }
    
    private void txtNamaAwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaAwalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaAwalActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int selectedRow = tableBank.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data yang ingin dihapus.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus data ini?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            tableModel.removeRow(selectedRow);
            clear();
            JOptionPane.showMessageDialog(this, "Data berhasil dihapus.");
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void txtSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSaldoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtSaldoActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:

        int selectedRow = tableBank.getSelectedRow();
        if (selectedRow >= -1) {
            String namaAwalLama = (String) tableModel.getValueAt(selectedRow, 0);
            String namaAkhirLama = (String) tableModel.getValueAt(selectedRow, 1);
            String namaAwalBaru = txtNamaAwal.getText();
            String namaAkhirBaru = txtNamaAkhir.getText();
            
            boolean status = bank.ubahNasabah(namaAwalLama, namaAkhirLama, namaAwalBaru, namaAkhirBaru);
            if (status){
                tableModel.setValueAt(namaAwalBaru, selectedRow, 0);
                tableModel.setValueAt(namaAkhirBaru, selectedRow, 1);
                JOptionPane.showMessageDialog(null, "Data berhasil diubah.");
                clear();
            } else {
                JOptionPane.showMessageDialog(null, "Gagal");
            }
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void tableBankMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBankMouseClicked
        // TODO add your handling code here:
        int selectedRow = tableBank.getSelectedRow();
        btnEdit.setEnabled(true);
        btnHapus.setEnabled(true);
        btnTarik.setEnabled(true);
        btnTambah.setEnabled(true);
        
        txtNamaAwal.setText((String) tableModel.getValueAt(selectedRow, 0));
        txtNamaAkhir.setText((String) tableModel.getValueAt(selectedRow, 1));
        txtSaldo.setText((String) tableModel.getValueAt(selectedRow, 2));
        
        txtSaldo.setEnabled(false);
    }//GEN-LAST:event_tableBankMouseClicked

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
            // TODO add your handling code here:
        int selectedRow = tableBank.getSelectedRow();
        if (selectedRow != -1) {
            String namaAwal = (String) tableModel.getValueAt(selectedRow, 0);
            String namaAkhir = (String) tableModel.getValueAt(selectedRow, 1);
            String saldo = (String) tableModel.getValueAt(selectedRow, 2);

            // Buat instance dari TambahView dan kirim data
            TambahView tambahView = new TambahView(this);
            tambahView.setData(namaAwal, namaAkhir, saldo, selectedRow);
            tambahView.setVisible(true);
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnTarikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarikActionPerformed
        // TODO add your handling code here:
        int selectedRow = tableBank.getSelectedRow();
        if (selectedRow != -1) {
            String namaAwal = (String) tableModel.getValueAt(selectedRow, 0);
            String namaAkhir = (String) tableModel.getValueAt(selectedRow, 1);
            String saldo = (String) tableModel.getValueAt(selectedRow, 2);

            // Buat instance dari TarikView dan kirim data
            TarikView tarikView = new TarikView(this);
            tarikView.setData(namaAwal, namaAkhir, saldo, selectedRow);
            tarikView.setVisible(true);
        }
    }//GEN-LAST:event_btnTarikActionPerformed

    private void tableBankMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBankMouseExited
        // TODO add your handling code here:
       
    }//GEN-LAST:event_tableBankMouseExited

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtSaldo.setEnabled(true);
        clear();
    }//GEN-LAST:event_btnResetActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BankView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BankView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BankView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BankView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BankView().setVisible(true);
            }
        });
        
    }

    public void updateSaldo(int rowIndex, int saldo) {
        tableModel.setValueAt(saldo, rowIndex, 2);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnTarik;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblNamaAkhir;
    private javax.swing.JLabel lblNamaAwal;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JTable tableBank;
    private javax.swing.JLabel titleBank;
    private javax.swing.JTextField txtNamaAkhir;
    private javax.swing.JTextField txtNamaAwal;
    private javax.swing.JTextField txtSaldo;
    // End of variables declaration//GEN-END:variables
}
